import pandas as pd
from pathlib import Path
from pylatex import Document, Section, Figure, Command, NoEscape, Tabular
from pylatex.package import Package

EXCEL_PATH = Path("fossee_inputs/beam_results.xlsx")
BEAM_IMAGE = Path("fossee_assets/simply_supported_beam.png")


def load_beam_data():
    df = pd.read_excel(EXCEL_PATH)

    required_cols = {"x", "Shear force", "Bending Moment"}
    if not required_cols.issubset(df.columns):
        raise ValueError("Excel must contain x, Shear force, Bending Moment")

    return df.sort_values("x").reset_index(drop=True)


def create_report(df):

    shear_coords = " ".join(f"({r.x},{r[1]})" for r in df.itertuples())
    moment_coords = " ".join(f"({r.x},{r[2]})" for r in df.itertuples())

    doc = Document()

    doc.packages.append(Package("geometry"))
    doc.packages.append(Package("graphicx"))
    doc.packages.append(Package("tikz"))
    doc.packages.append(Package("pgfplots"))

    doc.preamble.append(Command("title", "FOSSEE Structural Automation Report"))
    doc.preamble.append(Command("author", "Generated by mylatexfossee"))
    doc.preamble.append(Command("date", NoEscape(r"\today")))

    doc.append(NoEscape(r"\maketitle"))
    doc.append(NoEscape(r"\tableofcontents"))
    doc.append(NoEscape(r"\newpage"))

    # Introduction
    with doc.create(Section("Introduction")):
        doc.append("This report was created as part of the FOSSEE screening task using Python and PyLaTeX.")

    # Beam
    with doc.create(Section("Beam Description")):
        with doc.create(Figure(position="h!")):
            doc.append(NoEscape(r"\includegraphics[width=0.8\linewidth]{fossee_assets/simply_supported_beam.png}"))

    # Data Source
    with doc.create(Section("Data Source")):
        doc.append("Force values are read directly from the provided Excel file.")

    # Input Table
    with doc.create(Section("Input Data")):
        with doc.create(Tabular("|c|c|c|")) as table:
            table.add_hline()
            table.add_row(["x", "Shear Force", "Bending Moment"])
            table.add_hline()

            for _, row in df.iterrows():
                table.add_row([row["x"], row["Shear force"], row["Bending Moment"]])
                table.add_hline()

    # SFD
    with doc.create(Section("Shear Force Diagram")):
        doc.append(NoEscape(r"""
\begin{tikzpicture}
\begin{axis}[
width=14cm,
height=7cm,
grid=both,
xlabel={Beam Length (m)},
ylabel={Shear Force (kN)},
title={Shear Force Diagram},
legend style={at={(1.02,1)},anchor=north west},
axis lines=middle
]
\addplot+[thick,mark=*] coordinates {""" + shear_coords + r"""};
\addplot[dashed] coordinates {(0,0) (20,0)};
\legend{SFD,Zero Line}
\end{axis}
\end{tikzpicture}
"""))


    # BMD
    with doc.create(Section("Bending Moment Diagram")):
        doc.append(NoEscape(r"""
\begin{tikzpicture}
\begin{axis}[
width=14cm,
height=7cm,
grid=both,
xlabel={Beam Length (m)},
ylabel={Bending Moment (kNm)},
title={Bending Moment Diagram},
legend style={at={(1.02,1)},anchor=north west},
axis lines=middle
]
\addplot+[thick,mark=square*] coordinates {""" + moment_coords + r"""};
\addplot[dashed] coordinates {(0,0) (20,0)};
\legend{BMD,Zero Line}
\end{axis}
\end{tikzpicture}
"""))

    with doc.create(Section("Summary")):
        doc.append("""
Shear Force Diagram (SFD) shows how shear varies along the beam because of applied loads.

Bending Moment Diagram (BMD) shows bending behaviour of the beam. For a simply supported beam, maximum bending generally occurs near the middle span.

These diagrams are useful to understand critical sections of the beam before doing actual structural design.
""")


    doc.generate_pdf("fossee_output/beam_report", clean_tex=False, compiler="pdflatex", silent=True)


if __name__ == "__main__":
    df = load_beam_data()
    create_report(df)
    print("Reporr Generated Successfully.")


